import ProjectEstimation from '../model/project_estimation.js';
import Project from '../../project/model/project.model.js';
import fs from 'fs';
import path from 'path';
import PDFDocument from 'pdfkit';

function ensureUploadsDir() {
  const uploadsDir = path.join(process.cwd(), 'uploads');
  if (!fs.existsSync(uploadsDir)) {
    fs.mkdirSync(uploadsDir, { recursive: true });
  }
  return uploadsDir;
}

function safeFilePart(value) {
  return String(value ?? '')
    .trim()
    .replace(/\s+/g, '_')
    .replace(/[^a-zA-Z0-9._-]/g, '')
    .slice(0, 80);
}

async function writeEstimationPdf({ estimate, project }) {
  const uploadsDir = ensureUploadsDir();
  const projectNameSafe = safeFilePart(project?.projectName || 'Project');
  const filename = `${projectNameSafe}_Estimation_v${estimate.version}.pdf`;
  const filePath = path.join(uploadsDir, filename);

  const doc = new PDFDocument({ size: 'A4', margin: 50 });
  const stream = fs.createWriteStream(filePath);
  doc.pipe(stream);

  const createdAt = estimate?.createdAt ? new Date(estimate.createdAt) : new Date();

  doc
    .fontSize(18)
    .text('Project Estimation (Approved)', { align: 'center' })
    .moveDown(1);

  doc.fontSize(12);
  doc.text(`Project: ${project?.projectName || ''}`);
  doc.text(`Version: ${estimate.version}`);
  doc.text(`Status: ${estimate.status}`);
  doc.text(`Created: ${createdAt.toLocaleDateString()}`);
  if (estimate.approvedAt) {
    doc.text(`Approved: ${new Date(estimate.approvedAt).toLocaleDateString()}`);
  }
  if (estimate.remarks) {
    doc.moveDown(0.5);
    doc.text(`Remarks: ${estimate.remarks}`);
  }

  doc.moveDown(1);
  doc.fontSize(13).text('Cost Breakdown', { underline: true });
  doc.moveDown(0.5);
  doc.fontSize(12);

  const rows = [
    ['Labor', estimate.laborCost],
    ['Material', estimate.materialCost],
    ['Service', estimate.serviceCost],
    ['Contingency', estimate.contingencyCost],
    ['Total', estimate.total]
  ];

  for (const [label, val] of rows) {
    const amount = Number(val ?? 0);
    doc.text(`${label}: ${amount.toLocaleString()}`);
  }

  doc.moveDown(2);
  doc.fontSize(10).fillColor('gray').text('Generated by DesynFlow', { align: 'center' });
  doc.end();

  await new Promise((resolve, reject) => {
    stream.on('finish', resolve);
    stream.on('error', reject);
  });

  return {
    filename,
    path: `/api/uploads/${filename}`,
    originalName: `${project?.projectName || 'Project'} - Estimation v${estimate.version}.pdf`
  };
}

async function attachPdfToProject({ estimate, attachment }) {
  if (!estimate?.projectId) return;
  const project = await Project.findById(estimate.projectId);
  if (!project) return;

  const existing = Array.isArray(project.attachments) ? project.attachments : [];
  const next = existing.filter((a) => {
    if (!a) return false;
    if (typeof a === 'string') {
      return a !== attachment.path;
    }
    return a.path !== attachment.path && a.filename !== attachment.filename && a.originalName !== attachment.originalName;
  });

  next.push({
    filename: attachment.filename,
    originalName: attachment.originalName,
    path: attachment.path,
    uploadDate: new Date()
  });

  project.attachments = next;
  await project.save();
}

// Get only Approved estimations
async function getApprovedEstimates() {
  const estimations = await ProjectEstimation.find({ status: 'Approved' })
    .populate('projectId', 'projectName status progress')
    .populate('createdBy', 'name email')
    .populate('lastQuotationId', '_id version status')
    .sort({ createdAt: -1, version: -1 });
    
  console.log('[estimations] Found approved estimations:', estimations.map(e => ({
    id: e._id,
    project: e.projectId?.projectName || e.projectId?._id,
    version: e.version,
    quotationCreated: e.quotationCreated,
    lastQuotationId: e.lastQuotationId?._id
  })));
  
  return estimations;
}

async function resolveProject(projectId) {
  // Try direct _id match first
  let project = await Project.findById(projectId);
  if (!project) {
    // Fallback: maybe client passed custom projectId field value (stored in projectId field)
    project = await Project.findOne({ projectId });
  }
  return project;
}

async function createOrUpdateEstimate({ projectId, laborCost, materialCost, serviceCost, contingencyCost, status }) {
  const project = await resolveProject(projectId);
  if (!project) {
    throw new Error('Project not found for provided projectId');
  }
  const realProjectId = project._id;
  const latest = await ProjectEstimation.findOne({ projectId: realProjectId }).sort({ version: -1 });
  const version = latest ? latest.version + 1 : 1;
  const estimate = new ProjectEstimation({
    projectId: realProjectId,
    laborCost,
    materialCost,
    serviceCost,
    contingencyCost,
    version,
    status: status || 'Pending'
  });
  await estimate.save();
  if (!project.estimateCreated) {
    await Project.updateOne({ _id: realProjectId }, { estimateCreated: true });
  }
  return estimate;
}

async function setStatus(estimateId, status, remarks, userId) {
  const allowed = ['Pending', 'Approved', 'Rejected'];
  if (!allowed.includes(status)) throw new Error('Invalid status');
  
  // Prepare update object
  const updateData = { status };
  
  // Add audit trail fields based on status
  if (status === 'Approved') {
    updateData.approvedBy = userId;
    updateData.approvedAt = new Date();
    if (remarks) updateData.remarks = remarks;
    // Clear rejection fields if re-approving
    updateData.rejectedBy = undefined;
    updateData.rejectedAt = undefined;
  } else if (status === 'Rejected') {
    updateData.rejectedBy = userId;
    updateData.rejectedAt = new Date();
    if (remarks) updateData.remarks = remarks;
    // Clear approval fields if re-rejecting
    updateData.approvedBy = undefined;
    updateData.approvedAt = undefined;
  } else if (status === 'Pending') {
    // Clear all approval/rejection data when resetting to pending
    updateData.approvedBy = undefined;
    updateData.rejectedBy = undefined;
    updateData.approvedAt = undefined;
    updateData.rejectedAt = undefined;
    updateData.remarks = undefined;
  }
  
  const estimate = await ProjectEstimation.findByIdAndUpdate(
    estimateId,
    updateData,
    { new: true }
  );

  // When approved, generate a PDF and attach it to the project documents.
  if (estimate && status === 'Approved') {
    try {
      const project = await Project.findById(estimate.projectId).select('projectName');
      const attachment = await writeEstimationPdf({ estimate, project });
      await attachPdfToProject({ estimate, attachment });
    } catch (e) {
      // Non-fatal: approval should still succeed even if PDF attachment fails.
      console.warn('[estimations] Approved, but failed to generate/attach PDF:', e?.message || e);
    }
  }

  return estimate;
}

async function getEstimatesByProject(projectId) {
  return ProjectEstimation.find({ projectId }).sort({ version: -1 });
}

async function getAllEstimates() {
  return ProjectEstimation.find()
    .populate('projectId', 'projectName')
    .sort({ createdAt: -1 });
}

async function getLatestEstimate(projectId) {
  return ProjectEstimation.findOne({ projectId }).sort({ version: -1 });
}

export {
  createOrUpdateEstimate,
  setStatus,
  getEstimatesByProject,
  getAllEstimates,
  getLatestEstimate,
  getApprovedEstimates
};
