services:
  mongo:
    image: mongo:8.0.12
    container_name: desynflow-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  backend:
    build: ../server
    container_name: desynflow-backend
    ports:
      - "4000:4000"
    env_file:
      - ../server/.env
    volumes:
      - ../server:/app
      - /app/node_modules
    depends_on:
      - mongo
    command: npm start
    restart: unless-stopped

  staff-dashboard:
    build: ../frontend/staff-dashboard
    container_name: desynflow-staff-dashboard
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongo-data:

