version: "3.8"

services:
  mongo:
    image: mongo:8.0.12
    container_name: desynflow-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  backend:
    build: ../server
    container_name: desynflow-backend
    ports:
      - "4000:4000"
    env_file:
      - ../server/.env
    volumes:
      - ../server:/app
      - /app/node_modules
    depends_on:
      - mongo
    command: npm start
    restart: unless-stopped

  frontend:
    build: ../frontend/client-portal
    container_name: desynflow-frontend
    ports:
      - "3000:3000"
    volumes:
      - ../frontend/client-portal:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:4000
    command: npm start
    restart: unless-stopped

volumes:
  mongo-data:
